# Generated by Django 2.2.12 on 2023-04-23 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('nivel', models.CharField(choices=[('0', 'Ninguna'), ('1', '✪'), ('2', '✪✪'), ('3', '✪✪✪'), ('4', '✪✪✪✪'), ('5', '✪✪✪✪✪'), ('6', '✪✪✪✪✪✪'), ('7', '✪✪✪✪✪✪✪'), ('8', '✪✪✪✪✪✪✪✪'), ('9', '✪✪✪✪✪✪✪✪✪'), ('10', '✪✪✪✪✪✪✪✪✪✪'), ('11', '✪✪✪✪✪✪✪✪✪✪✪'), ('12', '✪✪✪✪✪✪✪✪✪✪✪✪')], max_length=50)),
                ('ataque', models.CharField(max_length=5)),
                ('defensa', models.CharField(max_length=5)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, default='image', null=True, upload_to='cartas/')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mazo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('carta_principal', models.CharField(max_length=50)),
                ('cantidad_de_cartas', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, default='image', null=True, upload_to='mazo/')),
            ],
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_torneo', models.CharField(max_length=50)),
                ('cantidad_participantes', models.IntegerField()),
                ('lugar_del_torneo', models.CharField(max_length=50)),
                ('premio', models.CharField(max_length=50)),
                ('codigo_de_torneo', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, default='image', null=True, upload_to='torneo/')),
            ],
        ),
    ]
